version: '2.2'
services:
  node:
    build:
      context: ./build
    container_name: rnode
    hostname: rnode
    restart: unless-stopped
    environment:
      ADNL_PORT:
      VALIDATOR_NAME:
      NETWORK_TYPE:
      CONFIGS_PATH:
      STATSD_DOMAIN:
      STATSD_PORT:
      STAKE:
      MSIG_ENABLE:
      SDK_URL:
      SDK_ENDPOINT_URL_LIST:
      TON_NODE_EXTRA_ARGS:
      TON_NODE_ENABLE_KAFKA:
      RUST_NET_ENABLE:
      ELECTOR_TYPE:
      DEPOOL_ENABLE:
      #SSH_AUTH_SOCK: /ssh-agent
    ports:
      - "${ADNL_PORT}:${ADNL_PORT}/udp"
    networks:
      - proxy_nw
    volumes:
      - ./configs/:/ton-node/configs/
      - ./scripts/:/ton-node/scripts/
      - ./logs/:/ton-node/logs/
      - DB:/ton-node/node_db/
      - /tmp/metrics/:/tmp/metrics/
      #- ${SSH_AUTH_SOCK}:/ssh-agent
    entrypoint: /ton-node/scripts/entrypoint.sh
    command: ["${NODE_CMD_1}", "${NODE_CMD_2}"]
    mem_limit: "${MEM_LIMIT}"
    logging:
      driver: json-file
      options:
        max-size: "1000m"
        max-file: "100"
    cap_add:
      - SYS_PTRACE
    extra_hosts:
      - "parser.service:127.0.0.1"
networks:
  proxy_nw:
    external: true
volumes:
  DB:
